
all:
	pio -f -c vim run

upload:
	pio -f -c vim run --target upload

clean:
	pio -f -c vim run --target clean

uploadfs:
	pio -f -c vim run --target uploadfs

update:
	pio -f -c vim update

fuses:
	pio run -t fuses

compile_commands:
	pio run --target compiledb

